name: hmm
channels:
  - conda-forge
dependencies:
  # Core Python
  - python=3.9

  # Numerical computing (pinned for pomegranate compatibility)
  - numpy=1.23.*
  - cython=0.29.*

  # HMM dependencies
  - pomegranate=0.14.*

  # Scientific computing (conda-forge versions compatible with NumPy 1.23)
  - scipy>=1.9,<1.12
  - scikit-learn>=1.1,<1.4

  # Additional dependencies for pomegranate
  - networkx
  - pyyaml
  - joblib

  # Gait analysis (will be installed via pip as it's not in conda-forge)
  - pip

  # Development tools
  - jupyterlab
  - matplotlib
  - pandas

  # Pip-installed packages
  - pip:
      - gaitmap>=2.0,<2.5  # Pin to avoid lazy import issues in 2.5.x
